version: '3'
services:
 db:
  image: postgres
  restart: always
  volumes:
    - './postgresdata:/var/lib/postgresql/data'
  environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=example
        - POSTGRES_DB=postgres
  healthcheck:
        test: ["CMD-SHELL", "pg_isready -h 0.0.0.0 -p 5432 -U postgres || exit 1"]
        interval: 15s
        timeout: 10s
        retries: 3
        start_period: 40s

 backend:
  build: ./backend
  restart: always
  environment:
        - DB_ENGINE=django.db.backends.postgresql
        - DB_CONNECTION=pgsql
        - DB_DATABASE=postgres
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASS=example
        - DB_HOST=db
        - DB_PORT=5432
        - SECRET_KEY='mxWcEKrrsrYkdvOqX7mdALlmZLtJgQeySXMAJ8DSZ1DegNpKz5GFzUfKDgiHpwHl'
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
        - ./backend:/backend
  ports:
        - "8000:8000"
  depends_on:
         db:
           condition: "service_healthy"

 frontend:
  build: ./frontend
  volumes:
   - ./frontend/:/app
   - '/app/node_modules'
  ports:
   - 3000:3000
  environment:
   - CHOKIDAR_USEPOLLING=true
   - HOST=0.0.0.0
#   - PORT=3000
